name: Deploy Azure Functions - The Printed Bay API

on:
  push:
    branches: [main]
    paths: ['front3nd/api/**']
  pull_request:
    branches: [main]
    paths: ['front3nd/api/**']
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'theprintedbay-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './front3nd/api'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/package-lock.json

    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm ci
        npm run build --if-present
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Health Check'
      run: |
        sleep 30
        curl -f ${{ steps.fa.outputs.app-url }}/api/health || exit 1
